cloud:
  aws:
    credentials:
      secret-key: rJMkAxN/e/W060o5Or3tt/mu9t9iBvy3IlEq9TwM
      access-key: AKIAQBGHLVIGAEPBQNMZ
    s3:
      bucket: junior-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: utf-8
jwt:
  secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWhhbmdoYWUtYXNzaWdubWVudC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleeKAmQo=
spring:
  datasource:
    password: junior1234
    username: admin
    url: jdbc:mysql://junior-test-db.ca6z3dxxsc7f.ap-northeast-2.rds.amazonaws.com:3306/booklog
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
